apiVersion: apps/v1
kind: Deployment
metadata:
  name: miniposra
spec:
  selector:
    matchLabels:
      app: miniposra
  replicas: 1
  template:
    metadata:
      labels:
        app: miniposra

    spec:
      containers:
      - name: miniposra
        image:  ${REPOSITORY_TAG}
        imagePullPolicy: Never
        


---


apiVersion: v1
kind: Service

metadata:
  name: miniposra

spec:
  selector:
    app: miniposra

  ports:
    - name: http
      port: 8888
     



  type:  ClusterIP

